apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mad:mad
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "local"
        ports:
        - containerPort: 8080
