apiVersion: v1	
kind: Service	
metadata:	
  name: backend	
  labels: # service monitor의 seletor을 위해 app 작성
    app: backend
spec:	
  ports:	
  - port: 80	
    targetPort: 8080	
    name: http
  selector:	
    app: backend
  type: ClusterIP
